version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: viserpaydb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/viserpaydb?schema=public
      VISERPAY_PUBLIC_KEY: 6lu3pf1kp4yfhsju1ufvf75gp646awbx8dvn1jsp7z5yiscx1e
      VISERPAY_SECRET_KEY: zhxhfpmxf6vtepz2hmbbz87sbxkwvb0hltzex9w7ygk5wae7lp
      VISERPAY_ENV: sandbox
      PORT: 3001
    ports:
      - '3001:3001'
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:3001
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres-data: